export const ADD_COMPANY = "ADD_COMPANY";
export const FETCH_COMPANY = "FETCH_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const ADD_OFFICE = "ADD_OFFICE";
export const FETCH_OFFICE = "FETCH_OFFICE";
export const DELETE_OFFICE = "DELETE_OFFICE";
